service: lambda-cron-sample-test-2

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: ap-south-1
  timeout: 6
  memorySize: 128
  stage: dev
  environment:
    AWS_PARAMETER_SPACE: theoldmonksqa15   
    AWS_LAMBDA_REGION: ap-south-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: 
            - "ssm:Describe*"
            - "ssm:Get*"
            - "ssm:List*"
          Resource: 
   layers:
   - arn:aws:lambda:us-east-1:177933569100:layer:AWS-Parameters-and-Secrets-Lambda-Extension:4 
   - arn:aws:lambda:us-east-1:268173716021:layer:aws-psycopg2-layer:2         - "*"
            
functions:
  rateHandler:
    name: ${self:custom.functionName}
    handler: handler.run
    description: Sample Cron Example

resources:
  Resources:
    CronJobTrigger:
      Type: AWS::Events::Rule
      Properties:        
        Name: lambda-cron-sample-test-2-scheduler
        Description: Invoke Lambda Function Every 1 Minute
        ScheduleExpression: cron(*/1 * * * ? *)
        State: ENABLED
        Targets:
          - Id: ${self:custom.functionName}
            Arn: arn:aws:lambda:${self:provider.region}:${aws:accountId}:function:${self:custom.functionName}
    LambdaInvokePermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName: ${self:custom.functionName}
        Action: lambda:InvokeFunction
        Principal: events.amazonaws.com
        SourceArn:
          Fn::GetAtt: [CronJobTrigger, Arn]
      DependsOn:
        - RateHandlerLambdaFunction  

custom:
  functionName: rateHandlerv2
